class AuthorizedRailsScaffolds::RSpecScaffoldControllerHelper < AuthorizedRailsScaffolds::RSpecScaffoldHelper
  include AuthorizedRailsScaffolds::Macros::ControllerMacros
  include AuthorizedRailsScaffolds::Macros::FactoryMacros
  include AuthorizedRailsScaffolds::Macros::RouteExampleMacros

  def initialize(options = {})
    super options

    # Modularized class name generated by spec generator
    @controller_class_name = options[:controller_class_name]
  end

  def build_example_index_params(*extra_params)
    [example_route_extra_params + extra_params].join(", ")
  end

  def build_example_show_params(*extra_params)
    [example_route_extra_params(shallow_routes?) + extra_params].join(", ")
  end

end