class AuthorizedRailsScaffolds::RSpecScaffoldControllerHelper < AuthorizedRailsScaffolds::RSpecScaffoldHelper
  include ControllerMacros
  include FactoryMacros
  include RouteExampleMacros

  def initialize(options = {})
    super options

    # Modularized class name generated by spec generator
    @controller_class_name = options[:controller_class_name]
  end

  def build_example_request_params(*extra_params)
    [example_route_extra_params + extra_params].join(", ")
  end

end